services:
  letsencrypt:
    build:
      context: .
      dockerfile: letsencrypt-dockerfile
    container_name: purebliss-letsencrypt
    volumes:
      - ./webroot:/mnt/raid0/nginx/html
      - ${LETSENCRYPT_CERT_PATH}:/etc/letsencrypt/live
    env_file:
      - /opt/my-secure-ha-stack/config.env
    networks:
      - purebliss-net
    healthcheck:
      test: ["CMD", "ls", "/etc/letsencrypt/live"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  purebliss-net:
    external: true
