global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['purebliss-nginx:80']

  # Vault
  - job_name: 'vault'
    static_configs:
      - targets: ['purebliss-vault:8200']

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['purebliss-grafana:3001']

  # Loki
  - job_name: 'loki'
    static_configs:
      - targets: ['purebliss-loki:3100']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['purebliss-redis:6379']

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['purebliss-postgres:5432']

  # Keycloak
  - job_name: 'keycloak'
    static_configs:
      - targets: ['purebliss-keycloak:8080']

  # Plane
  - job_name: 'plane'
    static_configs:
      - targets: ['purebliss-plane:8081']
