version: '3.8'
services:
  purebliss-grafana:
    image: grafana/grafana:10.1.0
    container_name: purebliss-grafana
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ${GRAFANA_DATA_PATH}:/var/lib/grafana
      - ${GRAFANA_LOG_PATH}:/var/log/grafana/grafana.log
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - purebliss-net
networks:
  purebliss-net:
    external: true
