# Keycloak Dockerfile (scaffolding phase)
# See centralized best practices in /opt/dev-purebliss/Documentation/
FROM quay.io/keycloak/keycloak:24.0.5

# Start Keycloak in development mode for scaffolding
# Use the standard entrypoint with start-dev command
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start-dev"]
