#!/bin/bash
set -euo pipefail

LOG_FILE="/opt/my-secure-ha-stack/logs/dev-environment-setup.log"
echo "[$(date)] INFO: Starting Redis container initialization" >> "$LOG_FILE"

# Environment variable validation and defaults
: "${VAULT_ADDR:=http://127.0.0.1:8200}"
: "${VAULT_SKIP_VERIFY:=true}"
: "${DB_ROLE:=redis-role}"
: "${USE_VAULT:=true}"
: "${REDIS_AUTH_ENABLED:=false}"
: "${REDIS_PASSWORD:=}"

echo "[$(date)] INFO: Redis entrypoint - VAULT_ADDR=$VAULT_ADDR, USE_VAULT=$USE_VAULT" >> "$LOG_FILE"

# Function to wait for Vault availability
wait_for_vault() {
    if [[ "$USE_VAULT" != "true" ]]; then
        echo "[$(date)] INFO: Vault integration disabled, skipping Vault checks" >> "$LOG_FILE"
        return 0
    fi

    echo "[$(date)] INFO: Waiting for Vault to be available..." >> "$LOG_FILE"
    for i in {1..30}; do
        if curl -sk "$VAULT_ADDR/v1/sys/health" >/dev/null 2>&1; then
            echo "[$(date)] INFO: Vault is ready" >> "$LOG_FILE"
            return 0
        fi
        if [[ $i -eq 30 ]]; then
            echo "[$(date)] WARNING: Vault not ready after 30 attempts, proceeding without Vault" >> "$LOG_FILE"
            export USE_VAULT="false"
            return 1
        fi
        sleep 2
    done
}

# Function to authenticate with Vault
vault_authenticate() {
    if [[ "$USE_VAULT" != "true" ]]; then
        return 0
    fi

    echo "[$(date)] INFO: Authenticating to Vault..." >> "$LOG_FILE"
    
    # Try AppRole authentication first
    if [[ -f "/run/secrets/vault-role-id" && -f "/run/secrets/vault-secret-id" ]]; then
        export VAULT_ROLE_ID=$(cat /run/secrets/vault-role-id)
        export VAULT_SECRET_ID=$(cat /run/secrets/vault-secret-id)
        echo "[$(date)] INFO: Using AppRole authentication" >> "$LOG_FILE"
        
        # Install jq if not available
        if ! command -v jq >/dev/null 2>&1; then
            apk add --no-cache jq curl
        fi
        
        TOKEN_RESPONSE=$(vault write -format=json auth/approle/login \
            role_id="$VAULT_ROLE_ID" \
            secret_id="$VAULT_SECRET_ID" 2>/dev/null || echo "null")
        
        if [[ "$TOKEN_RESPONSE" != "null" ]]; then
            export VAULT_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.auth.client_token')
            echo "[$(date)] INFO: AppRole authentication successful" >> "$LOG_FILE"
            return 0
        else
            echo "[$(date)] WARNING: AppRole authentication failed, trying dev token" >> "$LOG_FILE"
        fi
    fi
    
    # Fallback to dev token
    export VAULT_TOKEN="dev-root-token-purebliss"
    echo "[$(date)] INFO: Using dev token for Vault authentication" >> "$LOG_FILE"
}

# Function to retrieve Redis configuration from Vault
get_redis_config() {
    if [[ "$USE_VAULT" != "true" ]]; then
        echo "[$(date)] INFO: Using fallback Redis configuration" >> "$LOG_FILE"
        export REDIS_PASSWORD="${REDIS_PASSWORD:-}"
        export REDIS_AUTH_ENABLED="${REDIS_AUTH_ENABLED:-false}"
        return 0
    fi

    echo "[$(date)] INFO: Retrieving Redis configuration from Vault..." >> "$LOG_FILE"
    
    # Try to get Redis password from Vault KV store
    REDIS_CONFIG=$(vault kv get -format=json secret/redis/auth 2>/dev/null || echo "null")
    
    if [[ "$REDIS_CONFIG" != "null" ]]; then
        export REDIS_PASSWORD=$(echo "$REDIS_CONFIG" | jq -r '.data.data.password // empty')
        export REDIS_AUTH_ENABLED=$(echo "$REDIS_CONFIG" | jq -r '.data.data.auth_enabled // "false"')
        echo "[$(date)] INFO: Retrieved Redis configuration from Vault" >> "$LOG_FILE"
    else
        echo "[$(date)] WARNING: Could not retrieve Redis config from Vault, using defaults" >> "$LOG_FILE"
        export REDIS_PASSWORD=""
        export REDIS_AUTH_ENABLED="false"
    fi
}

# Function to configure Redis
configure_redis() {
    echo "[$(date)] INFO: Configuring Redis server..." >> "$LOG_FILE"
    
    # Create Redis configuration directory
    mkdir -p /usr/local/etc/redis
    
    # Generate Redis configuration
    cat > /usr/local/etc/redis/redis.conf <<EOF
# Redis Configuration - Generated by entrypoint.sh
# Bind to all interfaces for container networking
bind 0.0.0.0

# Enable protected mode for security
protected-mode yes

# Set the port
port 6379

# TCP listen backlog
tcp-backlog 511

# Close the connection after a client is idle for N seconds
timeout 0

# TCP keepalive
tcp-keepalive 300

# Logging
loglevel notice
logfile ""

# Set the number of databases
databases 16

# Enable AOF persistence for data durability
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# Memory management
maxmemory-policy allkeys-lru

# Security settings
EOF

    # Add authentication if enabled
    if [[ "$REDIS_AUTH_ENABLED" == "true" && -n "$REDIS_PASSWORD" ]]; then
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf
        echo "[$(date)] INFO: Redis authentication enabled" >> "$LOG_FILE"
    else
        echo "[$(date)] INFO: Redis authentication disabled" >> "$LOG_FILE"
    fi
    
    echo "[$(date)] INFO: Redis configuration created" >> "$LOG_FILE"
}

# Function to start Redis server
start_redis() {
    echo "[$(date)] INFO: Starting Redis server..." >> "$LOG_FILE"
    
    # Log the final configuration
    echo "[$(date)] INFO: Redis starting with auth_enabled=$REDIS_AUTH_ENABLED" >> "$LOG_FILE"
    
    # Start Redis server with configuration
    exec redis-server /usr/local/etc/redis/redis.conf
}

# Main execution flow
main() {
    echo "[$(date)] INFO: Redis container startup initiated" >> "$LOG_FILE"
    
    # Wait for Vault if enabled
    wait_for_vault
    
    # Authenticate to Vault if available
    vault_authenticate
    
    # Get Redis configuration from Vault
    get_redis_config
    
    # Configure Redis
    configure_redis
    
    # Start Redis server
    start_redis
}

# Execute main function
main "$@"
