version: '3.8'
services:
  purebliss-vault-agent:
    image: hashicorp/vault:1.17.3
    container_name: purebliss-vault-agent
    command: agent -config=/vault/config/config.hcl
    volumes:
      - ${VAULT_AGENT_CONFIG_PATH}:/vault/config/config.hcl:ro
      - ${VAULT_AGENT_OUTPUT_PATH}:/vault/agent
    depends_on:
      - purebliss-vault
    networks:
      - purebliss-net
networks:
  purebliss-net:
    external: true
