version: '3.8'
services:
  vault:
    image: hashicorp/vault:1.17.3
    container_name: vault-minimal-config
    ports:
      - "18220:18220"
    volumes:
      - ./myconfig.hcl:/vault/config/myconfig.hcl:ro
    command: server -config=/vault/config/myconfig.hcl
    networks:
      - purebliss-net
networks:
  purebliss-net:
    external: true
